### PR TITLE
Ease-of-Use Improvements

### PR DESCRIPTION
**Pull request by JukeboxRhino**
These improvements require the merging of @ssa3512's pull requests on [core](https://github.com/Storj/core/pull/701) and [storjshare-daemon](https://github.com/Storj/storjshare-daemon/pull/166).

- [x] Add port/connection column color coded to current connection status
- [x] Add timeserver delta with color coding
- [x] Add contract counter so farmers know when they are actively storing data for the network

Port colors

### CODE REVIEW

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: b8737ec5e64d946587f04274f50213555553a0c0
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-a06d46ee6fee521a4c57/storjshare-gui.amd64.deb)
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-a06d46ee6fee521a4c57/storjshare-gui.win32.exe)
[storjshare-gui.win64.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-a06d46ee6fee521a4c57/storjshare-gui.win64.exe)

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 97138223fcb0b315be51e39a62e412ef591d7574
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-a06d46ee6fee521a4c57/storjshare-gui.amd64.deb)

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: eeb862b0ca732699172f481279ca6588377e3029
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-a06d46ee6fee521a4c57/storjshare-gui.amd64.deb)
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-a06d46ee6fee521a4c57/storjshare-gui.win32.exe)

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 82d8041c4139b2c7c9f0d0afc91030aff337da83
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-a06d46ee6fee521a4c57/storjshare-gui.amd64.deb)
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-a06d46ee6fee521a4c57/storjshare-gui.win32.exe)
[storjshare-gui.win64.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-a06d46ee6fee521a4c57/storjshare-gui.win64.exe)

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: fb1c96cd7b373f033658604891bea9e08cbbd6bc
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-a06d46ee6fee521a4c57/storjshare-gui.amd64.deb)

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 8ced4f4a4e77b1e2ef2c96815819cf8c27534cdb
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-a06d46ee6fee521a4c57/storjshare-gui.amd64.deb)
[storjshare-gui.win64.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-a06d46ee6fee521a4c57/storjshare-gui.win64.exe)

**Comment by littleskunk** [comment]
Looks good to me

**Comment by MeijeSibbel** [comment]
Sam here, been running for a few days without any issues.

**Pull request merged**
