### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by bookchin**
**DO NOT MERGE UNTIL NEXT DEPLOYMENT**

### CODE REVIEW

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: c7a5e88509cfa565448f624b0ec6aa042427fc08
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-40b91bf2de751e7c03f5/storjshare-gui.amd64.deb)
[storjshare-gui.osx64.dmg](https://github.com/Storj/storjshare-gui/releases/download/untagged-40b91bf2de751e7c03f5/storjshare-gui.osx64.dmg)

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 0cc3df920840189ebb070ae7efb08425b9674966
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-5e0edb34b5316c48cfe2/storjshare-gui.amd64.deb)
[storjshare-gui.osx64.dmg](https://github.com/Storj/storjshare-gui/releases/download/untagged-5e0edb34b5316c48cfe2/storjshare-gui.osx64.dmg)
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-5e0edb34b5316c48cfe2/storjshare-gui.win32.exe)
[storjshare-gui.win64.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-5e0edb34b5316c48cfe2/storjshare-gui.win64.exe)

**Comment by littleskunk** [comment]
Wrong version of storj-telemetry-reporter

```
assert.js:85 Uncaught AssertionError: Invalid keypair suppliedfail @ assert.js:85ok @ assert.js:105TelemetryReporter @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\storj-telemetry-reporter\lib\telemetr…:22(anonymous function) @ client.js:258(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\lib\userdata.js:197(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\lib\utils.js:99(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\du\index.js:34(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\du\node_modules\async\lib\async.js:190(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\du\node_modules\async\lib\async.js:94(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\du\node_modules\async\lib\async.js:187(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\du\index.js:34(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\du\node_modules\async\lib\async.js:190(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\du\node_modules\async\lib\async.js:94(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\du\node_modules\async\lib\async.js:187(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\du\index.js:34(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\du\node_modules\async\lib\async.js:190(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\du\node_modules\async\lib\async.js:94(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\du\node_modules\async\lib\async.js:187(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\du\index.js:21(anonymous function) @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\graceful-fs\polyfills.js:279(anonymous function) @ fs.js:123
```

**Comment by bookchin** [comment]
Telemetry reporter bumped

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: a8366f1569c151252734569ab473b4a41fe46e90
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-5e0edb34b5316c48cfe2/storjshare-gui.amd64.deb)
[storjshare-gui.osx64.dmg](https://github.com/Storj/storjshare-gui/releases/download/untagged-5e0edb34b5316c48cfe2/storjshare-gui.osx64.dmg)
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-5e0edb34b5316c48cfe2/storjshare-gui.win32.exe)
[storjshare-gui.win64.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-5e0edb34b5316c48cfe2/storjshare-gui.win64.exe)

**Pull request merged**
