### PR TITLE
v1.0.0

### LINKED ISSUE #257: GUI white screen of death
Please add here any information you have. It will help us to find the reason.

### LINKED ISSUE #266: Rework UI
* Don't show the live log - use @aleitner's #265 to just write the log to a file (this may also solve our memory issues)
* Show only important status indicators like:
  - Last message received time
  - Connected peers
  - Space used
  - Last successful contract completed
  - SJCX balance
  - Link to open logfile

### LINKED ISSUE #269: Error: Invalid report supplied(…) undefined
I was a TGB user for several months with no issues. I took a break and now hope to re-join for TGB. However when installing the new client on WIN10 I get the following issue:
```
Vue warn]: Error when evaluating expression "tab.active": TypeError: Cannot read property 'active' of undefinedwarn @ C:\Program Files (x86)\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:1019
C:\Program Files (x86)\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:10069 Download the Vue Devtools for a better development experience:
https://github.com/vuejs/vue-devtools
client.js:420 [telemetry] sending report Object
client.js:422 [telemetry] null Success
client.js:420 [telemetry] sending report Object {storage: Object, bandwidth: Object, contact: Contact, payment: "12PV3X6Rq2kL9jdfuZD72NVP7Gh5jM6kvi"}
client.js:422 [telemetry] Error: Invalid report supplied(…) undefined
client.js:420 [telemetry] sending report Object {storage: Object, bandwidth: Object, contact: Contact, payment: "12PV3X6Rq2kL9jdfuZD72NVP7Gh5jM6kvi"}
client.js:422 [telemetry] Error: Invalid report supplied(…) undefined
client.js:420 [telemetry] sending report Object {storage: Object, bandwidth: Object, contact: Contact, payment: "12PV3X6Rq2kL9jdfuZD72NVP7Gh5jM6kvi"}
client.js:422 [telemetry] Error: Invalid report supplied(…) undefined
client.js:420 [telemetry] sending report Object {storage: Object, bandwidth: Object, contact: Contact, payment: "12PV3X6Rq2kL9jdfuZD72NVP7Gh5jM6kvi"}
client.js:422 [telemetry] Error: Invalid report supplied(…) undefined
```

repeating log entries:

```
{info} [Thu Jul 07 2016 21:32:42 GMT-0500 (Central Daylight Time)]
sending FIND_NODE message to {"protocol":"0.7.1","address":"108-90-22-140.lightspeed.cicril.sbcglobal.net","port":4000,"nodeID":"6735793f6e1041678aee205901fa7dc6548a10f6","lastSeen":1467945162954}
{error} [Thu Jul 07 2016 21:32:43 GMT-0500 (Central Daylight Time)]
failed to handle message, reason: Unexpected end of JSON input
 ```

### LINKED ISSUE #277: Add Terms
Display terms modal on first time start only.
https://github.com/Storj/storjshare-gui/tree/terms

### LINKED ISSUE #280: SJCX balance not showing
Running 0.9.1 and not seeing my SJCX balance.  Did not see it in the previous two releases either.  Running under Windows 7.

Problem tracked down to a leading space in settings.json's address field.

Recommend sanity checking that field during initial configuration to assure its valid.

### LINKED ISSUE #282: Does Not Handle Storage with TB Size
I set the share to a directory on a windows UNC share with about 22TB free space.  The UI only shows GB free with the wrong number.  I gave Storj 5TB of storage space and the Free Space display on the main UI only show GB free and the number is incorrect.

### LINKED ISSUE #285: Is the license correct?
AGPL is the project standard. Is there a compelling reason that this repo is GPL?

### PR DESCRIPTION
**Pull request by aleitner**
* Closes #257
* Closes #266 
* Closes #269 
* Closes #277
* Closes #280 
* Closes #282
* Closes #285

### CODE REVIEW

**Comment by bookchin** [comment]
Looks good to me! @littleskunk mind giving this a test yourself and draft a release if it all looks good?

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 8f73b9639c469f1ecbe96c23c4f814b5b88486f6
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-0b6beda75fe1c7579f87/storjshare-gui.amd64.deb)
[storjshare-gui.osx64.dmg](https://github.com/Storj/storjshare-gui/releases/download/untagged-0b6beda75fe1c7579f87/storjshare-gui.osx64.dmg)
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-0b6beda75fe1c7579f87/storjshare-gui.win32.exe)

**Comment by littleskunk** [comment]
Lets start with the good news.
GUI is looking good. Counter for connections and contracts are working. Used space and the progress bar is working as well.

Now the bad new:
1.) I set my log path to `D:\Storjshare` (selected via folder picker) but the logfiles are still stored in `%appdata%/Storj Share`. The View Log link is correct and open my logfolder`D:\Storjshare`.

2.) Reduce storage size. 20 MB used and new limit 10MB = 200% progress bar. The number is outside the screen and not readable. It would be nice if you could display the 200% number. If that is not possible cap it to 100%.

3.) Start farming, keep it running for a few minutes and stop farming. Developer console error message:
```
C:\Program Files (x86)\Storj Share\resources\app\node_modules\storj\lib\network\index.js:701 Uncaught TypeError: Cannot read property 'port' of null(anonymous function)
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\storj\lib\network\index.js:701(anonymous function)
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\async\lib\async.js:789(anonymous function)
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\async\lib\async.js:167(anonymous function)
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\storj\lib\network\index.js:690RPC._execPendingCallback
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\kad\lib\rpc.js:331(anonymous function)
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\kad\lib\rpc.js:235(anonymous function)
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\kad\lib\rpc.js:305(anonymous function)
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\async\lib\async.js:726(anonymous function)
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\async\lib\async.js:52(anonymous function)
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\async\lib\async.js:269(anonymous function)
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\async\lib\async.js:44(anonymous function)
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\async\lib\async.js:723(anonymous function)
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\async\lib\async.js:167protocol
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\kad\lib\hooks\protocol.js:21(anonymous function)
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\async\lib\async.js:718iterate
@ C:\Program Files (x86)\Storj Share\resources\app\node_modules\async\lib\async.js:262tryOnImmediate
@ timers.js:543processImmediate
@ timers.js:523
```
Looks like the telemetry report is still running and would like to send a new report.

4.) Start farming, stop farming and wait a few minutes. Start farming again. Developer console error message:
```
Uncaught Error: listen EADDRINUSE 0.0.0.0:4001exports._errnoException
@ util.js:949exports._exceptionWithHostPort
@ util.js:972Server._listen2
@ net.js:1253listen
@ net.js:1289(anonymous function)
@ net.js:1399_combinedTickCallback
@ internal/process/next_tick.js:77_tickCallback
@ internal/process/next_tick.js:98
```
Port 4001 is my tunnel server port. I am running my node with fixed ports.

5.) The Terms of Usage text had some coding problems.
```
entityâ€™s
Companyâ€™s
attorneysâ€™
individualâ€™s
```

Numer 5 must be fixed befor we can release it. The other 4 issues are not release important. My GUI node is farming stable even with these issues.

**Comment by boshevski** [comment]
Here is a pull req for fixing 5) the encoding issue in the terms
https://github.com/aleitner/storjshare-gui/pull/4

**Comment by boshevski** [comment]
Another pull req for the terms https://github.com/aleitner/storjshare-gui/pull/5

**Comment by bookchin** [comment]
I can fix number 4 today, we aren't shutting down the tunserver in `Network#leave`.

**Comment by bookchin** [comment]
Looks like I can fix 3 as well. Appears that closing the transport adapter triggers tunnel reestablishment which will fail.

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 8447e966db5375b89a31162087b3d22826567eda
[storjshare-gui.osx64.dmg](https://github.com/Storj/storjshare-gui/releases/download/untagged-0b6beda75fe1c7579f87/storjshare-gui.osx64.dmg)
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-0b6beda75fe1c7579f87/storjshare-gui.win32.exe)

**Comment by bookchin** [comment]
Almost finished with 3 and 4, will publish core 2.0.2 shortly

**Comment by littleskunk** [comment]
All issues fixed. Well done.

**Pull request merged**
