### PR TITLE
Disallow continuing past wizard step 3 with an empty/invalid directory

### PR DESCRIPTION
**Pull request by JukeboxRhino**
Adds a simple path check to make sure the config path is valid, otherwise the user might continue past without selecting a valid directory, which can cause some weird issues [(#1)](https://github.com/Storj/storjshare-gui/issues/521) [(#2)](https://github.com/Storj/storjshare-gui/issues/519)

I also removed the unneeded `fs` require as it is not being used in this page.

### CODE REVIEW

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 1104c8f7feac64a6cf6f933084df1667d3746096
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-a0fc76c0d80e94d30619/storjshare-gui.amd64.deb)
[storjshare-gui.osx64.dmg](https://github.com/Storj/storjshare-gui/releases/download/untagged-a0fc76c0d80e94d30619/storjshare-gui.osx64.dmg)
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-a0fc76c0d80e94d30619/storjshare-gui.win32.exe)
[storjshare-gui.win64.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-a0fc76c0d80e94d30619/storjshare-gui.win64.exe)

**Comment by littleskunk** [comment]
```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.isAbsolute (path.js:439:5)
    at VueComponent.pathIsValid (C:\Program Files\Storj Share\resources\app\views\share-wizard\wizard2.js:14:19)
    at Proxy.boundFn (C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:167:12)
    at Proxy.eval (eval at makeFunction (C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:9332:12), <anonymous>:2:638)
    at VueComponent.Vue._render (C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:3905:22)
    at VueComponent.updateComponent (C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:2441:21)
    at Watcher.get (C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:2780:25)
    at new Watcher (C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:2763:12)
    at mountComponent (C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:2445:17)
    at VueComponent.Vue$3.$mount (C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:7573:10)
    at VueComponent.Vue$3.$mount (C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:9672:16)
    at init (C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:3360:13)
    at createComponent (C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:4903:9)
    at createElm (C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:4846:9)
    at updateChildren (C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:5126:11)
handleError @ C:\Program Files\Storj Share\resources\app\node_modules\vue\dist\vue.common.js:525
```

Steps to reproduce:
select valid storage location
select a high storage allocation -> invalid size error
go back to storage location -> white page and exception on developer console

**Comment by JukeboxRhino** [comment]
There seems to be a recurring theme here with whenever a user clicks "Go Back" in the wizard, all of their data on every step is lost instead of being preserved. I'll try to discover why that is the case.

**Comment by JukeboxRhino** [comment]
Majorly screwed up git with this one, will re-open once I get sorted out

**Pull request closed without merging**
