### PR TITLE
Add Windows Firewall Rule

### PR DESCRIPTION
**Pull request by MysticRyuujin**
I'm not certain about the variable expansion in the command. I'm not familiar with NSIS so someone else should verify that part. Also I don't know if I need `!include nsExec.nsh` at the top? Needs tested...

### CODE REVIEW

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: a8f25c166917ef4d23308e58eac212126b032bb3
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-4f9b37c1bf074282e643/storjshare-gui.win32.exe)
[storjshare-gui.win64.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-4f9b37c1bf074282e643/storjshare-gui.win64.exe)
[storjshare-gui.osx64.dmg](https://github.com/Storj/storjshare-gui/releases/download/untagged-4f9b37c1bf074282e643/storjshare-gui.osx64.dmg)
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-4f9b37c1bf074282e643/storjshare-gui.amd64.deb)
[storjshare-gui.i386.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-4f9b37c1bf074282e643/storjshare-gui.i386.deb)

**Comment by MysticRyuujin** [comment]
@azrin619 can you test it?

**Comment by littleskunk** [comment]
@MysticRyuujin Please join dev channel on https://community.storj.io/

I am uploading the test binaries there.

**Comment by MysticRyuujin** [comment]
It looks like the variable INSTDIR was not expanded during execution, resulting in:

`HostApplication=powershell -Command { New-NetFirewallRule -DisplayName 'Storj Share' -Direction Inbound -Program '${INSTDIR}\Storj Share.exe' -Action allow }`

**Comment by MysticRyuujin** [comment]
The use of a Script Block ({ }) only works when running PowerShell in PowerShell otherwise -Command must be a string. I verified that the command itself does work when ran directly.

**Comment by MysticRyuujin** [comment]
Worked!

storjpowershellsuccess

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 5549b8c0dabbbe0ac3de297b6e332511569c88fc
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-4f9b37c1bf074282e643/storjshare-gui.amd64.deb)
[storjshare-gui.osx64.dmg](https://github.com/Storj/storjshare-gui/releases/download/untagged-4f9b37c1bf074282e643/storjshare-gui.osx64.dmg)
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-4f9b37c1bf074282e643/storjshare-gui.win32.exe)
[storjshare-gui.win64.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-4f9b37c1bf074282e643/storjshare-gui.win64.exe)

**Pull request merged**
