### PR TITLE
Sign windows binary

### LINKED ISSUE #36: Execution blocked by Windows 10 SmartScreen
I tryed DriveShare_0.3.0.exe. Windows 10 SmartScreen blocked it. Publisher information is missing. Thats why SmartScreen blocks it.

### PR DESCRIPTION
**Pull request by littleskunk**
Solves #36

### CODE REVIEW

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 8f13fc7a2e3a798d3679848c79c6a79b1f9f5211
[storjshare-gui.osx64.dmg](https://github.com/Storj/storjshare-gui/releases/download/untagged-49ac26858fead192ca83/storjshare-gui.osx64.dmg)
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-49ac26858fead192ca83/storjshare-gui.win32.exe)

**Comment by littleskunk** [comment]
The binary is signed but Windows Smart Screen is still blocking it.

**Comment by littleskunk** [comment]
```
C:\Users\Skunk\Downloads>signtool verify storjshare-gui.win32.exe
File: storjshare-gui.win32.exe
Index  Algorithm  Timestamp
========================================
SignTool Error: A certificate chain processed, but terminated in a root
        certificate which is not trusted by the trust provider.

Number of errors: 1
```

**Comment by littleskunk** [comment]
@super3 solved my problem here: https://github.com/Storj/storjshare-gui/issues/36#issuecomment-236582134

The signature is correct but we need reputation for our certificate. Pull request ready to merge.

On the next storjshare-gui release I will upload the signed binary to microsoft in order to increase the reputation.

**Comment by super3** [comment]
@littleskunk Mergeable?

**Pull request merged**
