### PR TITLE
Windows Firewall Installer and Uninstaller Prompt

### PR DESCRIPTION
**Pull request by MysticRyuujin**
I think this will prompt the user with a checkbox for the Windows Firewall option and it should also prompt for removal during uninstall. @littleskunk if you build it I'll test it.

### CODE REVIEW

**Comment by littleskunk** [comment]
image

Installer and Uninstaller are having a hidden checkbox. By using TAB I can select it but I can't see it.

**Comment by littleskunk** [comment]
That looks better:

image

**Comment by littleskunk** [comment]
image

**Comment by littleskunk** [comment]
The installer is working fine. It will add the fireware rule.

Removing the firewall rule was not working. Even if I select it the firewall rule is still active.

**Comment by MysticRyuujin** [comment]
Ok I updated the removal script, it should work now. I tested it manually. I'm a little concerned about the label in the Uninstaller. Notice how it's cut off on your screen? Is that normal? Does the old installer do that too? We might have to shrink the width or return to percentage or something.

**Comment by littleskunk** [comment]
Old Uninstaller:
image

**Comment by littleskunk** [comment]
The label is not that important. Lets merge this pull request and we start a new one to fix the line break. I don't want to risk the current state. Its works realy good. Well done and thank you.

**Pull request merged**
