### PR TITLE
ETH Support

### PR DESCRIPTION
**Pull request by JukeboxRhino**
- [x] Adds support for Ethereum address in the wizard. Checks to make sure user is entering valid Ethereum address, does not let them continue otherwise.
- [x] If the user has any nodes not using an Ethereum address when the program starts they are directed to another page with a short informational snippet about the migration. This page also includes links to supported ERC20 wallets. Input field checks for a valid Ethereum address here too, but allows them to return to the overview in the top left.
Image 1
Image 2

### CODE REVIEW

**Comment by aleitner** [comment]
As cool and big as your Ethereum address check method is, can you use this method instead. I forgot to release it when I wrote it so I just updated storjshare daemon v3.2.0 to include it. So be sure to update your PR to master to update your package.json https://github.com/Storj/storjshare-daemon/blob/master/lib/utils.js#L31

**Comment by aleitner** [comment]
Also we probably want to change the wizard1.js page to include the new wallet links too

**Comment by JukeboxRhino** [comment]
Will do both of those in approx. 7-8 hours

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: d2b96365ab2c862d3b0ad5ef3447855b936199ea
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-3b0df75214188a06db01/storjshare-gui.amd64.deb)
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-3b0df75214188a06db01/storjshare-gui.win32.exe)

**Pull request merged**
