### PR TITLE
Add Gibibyte for GUI user

### PR DESCRIPTION
**Pull request by littleskunk**

### CODE REVIEW

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 8708ccbb43cdb399ecd3a78f2aac6e795cb90086
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-3df4dd45d70a346fa022/storjshare-gui.amd64.deb)
[storjshare-gui.osx64.dmg](https://github.com/Storj/storjshare-gui/releases/download/untagged-3df4dd45d70a346fa022/storjshare-gui.osx64.dmg)
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-3df4dd45d70a346fa022/storjshare-gui.win32.exe)
[storjshare-gui.win64.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-3df4dd45d70a346fa022/storjshare-gui.win64.exe)

**Comment by littleskunk** [comment]
Depends on https://github.com/Storj/core/pull/559
The test binaries are build with my open pull request.

Gibibyte vs Gigabyte
screenshot

**Comment by bookchin** [comment]
Needs rebase

**Comment by littleskunk** [comment]
[autobin](https://github.com/Storj/autobin) binaries (only available for team members)
last commit: 1c15a572d3556356272eabbb583b3e4d1b57d22d
[storjshare-gui.amd64.deb](https://github.com/Storj/storjshare-gui/releases/download/untagged-3df4dd45d70a346fa022/storjshare-gui.amd64.deb)
[storjshare-gui.osx64.dmg](https://github.com/Storj/storjshare-gui/releases/download/untagged-3df4dd45d70a346fa022/storjshare-gui.osx64.dmg)
[storjshare-gui.win32.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-3df4dd45d70a346fa022/storjshare-gui.win32.exe)
[storjshare-gui.win64.exe](https://github.com/Storj/storjshare-gui/releases/download/untagged-3df4dd45d70a346fa022/storjshare-gui.win64.exe)

**Comment by littleskunk** [comment]
Rebased and ready to merge. Test binaries up to date.

New Screenshots:
screenshot

**Pull request merged**
